name: Lint

on: [pull_request, push]

jobs:
    lint_python:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - run: pip install --upgrade pip wheel
            - run: pip install bandit black flake8 flake8-bugbear flake8-comprehensions isort safety mypy
            - run: mypy --install-types --non-interactive --ignore-missing-imports ./rembg
            - run: bandit --recursive --skip B101,B104,B310,B311,B303 --exclude ./rembg/_version.py ./rembg
            - run: black --force-exclude rembg/_version.py --check --diff ./rembg
            - run: flake8 ./rembg --count --ignore=B008,C901,E203,E266,E731,F401,F811,F841,W503 --max-line-length=120 --show-source --statistics --exclude ./rembg/_version.py
            - run: isort --check-only --profile black ./rembg
            - run: safety check
